/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    ChannelList: typeof import('./../components/device/ChannelList.vue')['default']
    Column: typeof import('primevue/column')['default']
    CreateChannel: typeof import('./../components/device/CreateChannel.vue')['default']
    CreateDevice: typeof import('./../components/device/CreateDevice.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DeviceCard: typeof import('./../components/device/DeviceCard.vue')['default']
    DeviceList: typeof import('./../components/device/DeviceList.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    DMXChannel: typeof import('./../components/dmx/DMXChannel.vue')['default']
    DMXController: typeof import('./../components/dmx/DMXController.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Listbox: typeof import('primevue/listbox')['default']
    Menubar: typeof import('primevue/menubar')['default']
    ModalBody: typeof import('./../components/settings/universe/modal/ModalBody.vue')['default']
    ModalHeader: typeof import('./../components/settings/universe/modal/ModalHeader.vue')['default']
    NavigationMenu: typeof import('./../components/common/NavigationMenu.vue')['default']
    Paginator: typeof import('primevue/paginator')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollPanel: typeof import('primevue/scrollpanel')['default']
    SettingsPanel: typeof import('./../components/settings/SettingsPanel.vue')['default']
    SettingsUI: typeof import('./../components/settings/SettingsUI.vue')['default']
    Slider: typeof import('primevue/slider')['default']
    SocketListener: typeof import('./../components/settings/universe/SocketListener.vue')['default']
    SocketProvider: typeof import('./../components/common/SocketProvider.vue')['default']
    Stepper: typeof import('primevue/stepper')['default']
    SwitchTheme: typeof import('./../components/settings/SwitchTheme.vue')['default']
    ToggleButton: typeof import('primevue/togglebutton')['default']
    UniverseSelect: typeof import('./../components/settings/universe/UniverseSelect.vue')['default']
  }
}
